"""init rbac

Revision ID: c3d95cb0f5d9
Revises: 
Create Date: 2026-05-30 13:34:18.071136

"""
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d95cb0f5d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_permissions_created_time'), 'permissions', ['created_time'], unique=False)
    op.create_index(op.f('ix_permissions_updated_time'), 'permissions', ['updated_time'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_created_time'), 'roles', ['created_time'], unique=False)
    op.create_index(op.f('ix_roles_updated_time'), 'roles', ['updated_time'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_time'), 'users', ['created_time'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_updated_time'), 'users', ['updated_time'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )

    permissions_table = sa.table('permissions', sa.column('name'))
    op.bulk_insert(
        permissions_table,
        [
            {"name": "user:create"},
            {"name": "user:read"},
            {"name": "user:update"},
            {"name": "user:delete"},
        ],
    )
    roles_table = sa.table('roles', sa.column('name'))
    op.bulk_insert(
        roles_table,
        [
            {"name": "admin"},
            {"name": "user"},
        ],
    )

    users_table = sa.table('users', sa.column('id'), sa.column('username'), sa.column('password'))
    op.bulk_insert(
        users_table,
        [
            {"id": str(uuid.uuid4()), "username": "admin", "password": "admin123"},
        ],
    )

    op.execute("""
    INSERT INTO role_permissions (role_id, permission_id)
    SELECT r.id, p.id
    FROM roles r
    CROSS JOIN permissions p
    WHERE r.name = 'admin'
    """)

    op.execute("""
    INSERT INTO role_permissions (role_id, permission_id)
    SELECT r.id, p.id
    FROM roles r
    JOIN permissions p ON p.name IN ('user:read', 'user:update')
    WHERE r.name = 'user'
    """)

    op.execute("""
    INSERT INTO user_roles (user_id, role_id)
    SELECT u.id, r.id
    FROM users u
    JOIN roles r ON r.name = 'admin'
    WHERE u.username = 'admin'
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_updated_time'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_time'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_updated_time'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_time'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_updated_time'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_created_time'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
